### ISSUE TITLE
Penamaan function pada latihan1 : "oddNumber"

### ISSUE THREAD

**Issue by rmRizki** [dicodingacademy/proyek-submission-mpk#1]
Soal dan test case yang diminta adalah pengecekan angka genap (even number), namun function yang ditulis adalah **oddNumber**.

```
/**
 *  TODO 1
 *  Sesuaikan fungsi di bawah ini dengan kode untuk mengecek apakah parameter number
 *  merupakan angka genap
 */
fun oddNumber(number: Int) = false
```

Link [discussion](https://www.dicoding.com/academies/80/discussions/147003)

**Comment by alfianyusufabdullah** [comment]
Hallo @rmRizki , terima kasih atas laporannya. Untuk penamaan yang keliru sudah diperbaiki ya. 

[#df7328f](https://github.com/dicodingacademy/proyek-submission-mpk/commit/df7328fadb3100199a74d3a8713b907b4c502538)
